### ISSUE TITLE
feature: use env! macro to throw error's at compile time.

### ISSUE THREAD

**Issue by fastfists** [arguflow/arguflow#246]
This is for the `server` folder. Everywhere than an `env` var is loaded should throw an error at compile if it is not present once this issue is resolved.

However, the exception is env vars that are optional. Do not make them required please.

**Comment by skeptrunedev** [comment]
> /attempt #246
> 
> Options

Hey, please don't require env vars that are optional. If they have an `unwrap_or` or something similar then we want to allow them to not be set.

**Comment by tobihans** [comment]
> > /attempt #246
> > 
> > Options
> 
> Hey, please don't require env vars that are optional. If they have an `unwrap_or` or something similar then we want to allow them to not be set. 
> 
> <details id="algora-options">
>   <summary>Options</summary>
>   <ul>
>     <li>
>       <a href="https://console.algora.io/api/bounties/clmo5x1ot0002ma0f3nfk83sd/cancel-attempt">
>         Cancel my attempt
>       </a>
>     </li>
>   </ul>
> </details>
> 

Oh yeah, I'll fix that. Thanks
