### ISSUE TITLE
cleanup: remove everything to do with async_stripe in `server` 

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#430]
At some point it may be nice to add this back, but it is not needed for now. 

The business model has shifted away from SaaS such that this code is only making compilation take longer. 

completion requirement: `async_stripe` can be removed as a crate

**Comment by RamK777-stack** [comment]
@fastfists How to get the bounty, I have added /claim in PR comments. even PR merged bounty hasn't been received yet. Can you please look into this.

**Comment by skeptrunedev** [comment]
> @fastfists How to get the bounty, I have added /claim in PR comments. even PR merged bounty hasn't been received yet. Can you please look into this.

Should be paid now! Sorry about that!

**Comment by RamK777-stack** [comment]
Thank you so much !! @skeptrunedev
