### ISSUE TITLE
developer experience: unify ts/js/tailwind config files between `search` and `chat` folders

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#431]
Right now there are multiple config files present between `chat` and `search` which are causing issues. We would like to modify the folder such that the configurations are unified. Here are a list of files to remove and place in the root dir: 

- [ ] `postcss.config.cjs`
- [ ] `prettier.cofnig.cjs`
- [ ] `tailwind.config.cjs`
- [ ] `tsconfig.json`

## Bounty acceptance requirement

We must be able to work in the `search` and `chat` projects when we have `arguflow/arguflow` open and not see any red squiggles.

**Comment by fastfists** [comment]
This one might as well have a top level package.json

**Comment by skeptrunedev** [comment]
> This one might as well have a top level package.json

Idk if that is even possible

**Comment by rishi-raj-jain** [comment]
Can I work on this?

**Comment by skeptrunedev** [comment]
> Can I work on this?

Have at it. Only requirement is to finish first. We will give the bounty to the first person who has a valid PR. :)

**Comment by skeptrunedev** [comment]
> Can I work on this?

Also star the repo! :wink:

**Comment by rishi-raj-jain** [comment]
Both the tsconfigs are different in nature, but I can still place them in the root dir and extend it from there. I don't think this though removes them from their respective folders they are already in. Same for prettier config, tailwind.config.cjs.

Basically the common parts can go to the root but the files would still needed to be in each folder as they all totally seperate.

**Comment by skeptrunedev** [comment]
> Both the tsconfigs are different in nature, but I can still place them in the root dir and extend it from there. I don't think this though removes them from their respective folders they are already in. Same for prettier config, tailwind.config.cjs.
> 
> Basically the common parts can go to the root but the files would still needed to be in each folder as they all totally seperate.

Hmmm, the thing we really care about here is being able to work in the `chat` and `search` projects w/out VSCode throwing up red squiggles.

**Comment by rishi-raj-jain** [comment]
>  w/out VSCode throwing up red squiggles.

So, if you open the search and chat individually in VS Code then it shall be working fine without the red marks, correct?

You mean when you're opening the whole arguflow folder in VS Code, right?

**Comment by skeptrunedev** [comment]
> > w/out VSCode throwing up red squiggles.
> 
> So, if you open the search and chat individually in VS Code then it shall be working fine without the red marks, correct?
> 
> You mean when you're opening the whole arguflow folder in VS Code, right?

Correct. Ideally we don't want VSCode users to be required to open 3 separate electron windows to work on the project

**Comment by rishi-raj-jain** [comment]
@skeptrunedev Would love to get the bounty set on this!

**Comment by rishi-raj-jain** [comment]
@skeptrunedev Thank you so much!
