### ISSUE TITLE
bugfix: link and tag_set filters are not applying strictly 

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#432]
### How to replicate 

1. Create some cards with links and tagsets (feel free to reach out on Matrix for help on this piece) 
2. Open up the search UI locally and click the `filters` dropdown 
3. Add some `link` and `tagset` filter which fits your data
4. Type a search query and press enter
5. You should be able to see that there are results which do not strictly adhere to your filters 

### Likely issue

In `card_operator.rs` there are multiple instances of ` query = query.filter` for the first element in the array then `query = query.or_filter` for the subsequent indices. The first `.filter` should force all at least one of the filtered conditions in the set to apply, but that does not appear to be happening. 

### Deliverables for completion 

- [ ] diagnostics: determine why the filters are not applying strictly 
- [ ] bugfix: modify the code everywhere that a filter applies for `tag_set` or `link` such that it is strict

**Comment by skeptrunedev** [comment]
![filters-are-not-strict](https://github.com/arguflow/arguflow/assets/15804464/179c2f84-a032-40a8-b6cc-b5103062ed5c)

**Comment by akhill10** [comment]
I am working on this bug 

/attempt #432

**Comment by skeptrunedev** [comment]
Closing as @densumesh did not have the same issue. May re-open in the future, but unlikely.

**Comment by Narottamchy** [comment]
is it open

**Comment by skeptrunedev** [comment]
> is it open

No
