### ISSUE TITLE
feature: make it easy to disable SSR and require auth for all routes

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#433]
### Description

Currently several routes on the `server` do not require authentication. The idea of this is to allow for the `search` UI to have SSR. There are use-cases where this behavior is not desired and auth should be required for all routes; i.e. semantic search over discovery docs for legal teams. 

### Target(s)

`server`, `search`

### Requirement to close

- [ ] feature: env for `search` that disables SSR for all pages
- [ ] feature: mechanism (feature flag or env) that requires auth on every route for `server`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by rishi-raj-jain** [comment]
I'd love to work on this!

>  feature: env for search that disables SSR for all pages

I see many pages doing upstream API calls, say https://github.com/arguflow/arguflow/blob/main/search/src/pages/index.astro for example. When an env is present to not SSR pages, do we want to render those parts but in client side or not want to show these parts at all/

**Comment by skeptrunedev** [comment]
> I'd love to work on this!
> 
> > feature: env for search that disables SSR for all pages
> 
> I see many pages doing upstream API calls, say https://github.com/arguflow/arguflow/blob/main/search/src/pages/index.astro for example. When an env is present to not SSR pages, do we want to render those parts but in client side or not want to show these parts at all?

Still render client side. You have to add/change to `client:only` for the components that are currently being SSR'ed or `client:load`'ed when thr feature .env flag is set.

**Comment by rishi-raj-jain** [comment]
> Still render client side. You have to add/change to client:only for the components that are currently being SSR'ed or client:load'ed when the feature .env flag is set.

Thanks! But just want to make sure that we're aware with client:only the component gets loaded as client is mounted, but the data fetch still occurs on the server (before the page is streamed into the browser). So by turning off SSR you mean that just the components get client side render?

**Comment by rishi-raj-jain** [comment]
Also, can you split this into two? I'm not a rust expert but for sure I know Astro in a good amount. I'd love to work on adding that env for `search` project.

**Comment by rishi-raj-jain** [comment]
I can raise a PR and then you can tip by method as mentioned in https://docs.algora.io/tipping#:~:text=directly%20specifying%20their-,username,-as%20in%20/tip

**Comment by rishi-raj-jain** [comment]
Make sense?

**Comment by skeptrunedev** [comment]
> Also, can you split this into two? I'm not a rust expert but for sure I know Astro in a good amount. I'd love to work on adding that env for `search` project.

Unfortunately this is one that makes much more sense to do together. The Astro piece w/out the server being updated isn't all that helpful.

**Comment by rishi-raj-jain** [comment]
The `env` is independent for search and server, correct?

**Comment by rishi-raj-jain** [comment]
What I mean is that one of the items can get ticked off for this one, and the rust contributors can chime in then...

**Comment by skeptrunedev** [comment]
> > Still render client side. You have to add/change to client:only for the components that are currently being SSR'ed or client:load'ed when the feature .env flag is set.
> 
> Thanks! But just want to make sure that we're aware with client:only the component gets loaded as client is mounted, but the data fetch still occurs on the server (before the page is streamed into the browser). So by turning off SSR you mean that just the components get client side render?

The requests being made in the frontmatter of the Astro files before the fence need to be disabled in non SSR mode, yes.

In places where this breaks things, the code will have to be updated such that it is fixed.

**Comment by skeptrunedev** [comment]
> What I mean is that one of the items can get ticked off for this one, and the rust contributors can chime in then...

Yeah, I understand. But we want these done at the same time. Not much of a point to split it up. The Rust piece here is very trivial, you should try it!

**Comment by rishi-raj-jain** [comment]
Oh okay, on it then :D

**Comment by rishi-raj-jain** [comment]
@skeptrunedev 

Also, sidetrack: https://github.com/arguflow/vault-chat/issues/17 is it available for grab?

**Comment by skeptrunedev** [comment]
> /attempt #433
> 
> Oh okay, on it then :D
> 
> Options

If you get stuck on the Rust piece, ping me, @fastfists or @densumesh and one of us will help.

**Comment by skeptrunedev** [comment]
> @skeptrunedev
> 
> Also, sidetrack: [arguflow/vault-chat#17](https://github.com/arguflow/vault-chat/issues/17) is it available for grab? I see the repo is archived, so where does it need to be worked on?

No. Let me close that right now.

**Comment by rishi-raj-jain** [comment]
> f you get stuck on the Rust piece, ping me, @fastfists or @densumesh and one of us will help.

For sure, I'll keep that in mind, first learning the entrypoint of rust, where are the endpoints, and how to use env in rust...

**Comment by rishi-raj-jain** [comment]
Would love any guidance on the same

**Comment by rishi-raj-jain** [comment]
@skeptrunedev are the following the rust endpoints that require the check?

<img width="259" alt="Screenshot 2023-09-19 at 1 34 53 PM" src="https://github.com/arguflow/arguflow/assets/46300090/4e4b97df-3504-4014-9180-3cc9ee359681">

**Comment by rishi-raj-jain** [comment]
Ah I see, I can do it on https://github.com/arguflow/arguflow/blob/main/server/src/lib.rs#L149, correct?

**Comment by skeptrunedev** [comment]
Yo @rishi-raj-jain , did you see my email about hiring you as a contractor at an hourly rate? 

You have been doing really great work, and we think it makes sense to have you working on Arguflow more consistently so you can take bigger tickets and projects.

**Comment by ogil7190** [comment]
@skeptrunedev can i attempt it?

**Comment by skeptrunedev** [comment]
> @skeptrunedev can i attempt it?

Go ahead! And don't forget to star the repo if you haven't yet :heart: . 

![image](https://github.com/arguflow/arguflow/assets/15804464/1470a9e7-9b2e-4032-9380-83ae7a332e43)

**Comment by ogil7190** [comment]
@skeptrunedev If i understood the requirements clearly 
1. You want yourSearch UI to disable SSR based on an ENV variable right?
2. You want to enable auth for every route in the server based on an ENV variable right?

**Comment by skeptrunedev** [comment]
> @skeptrunedev If i understood the requirements clearly
> 
> 1. You want yourSearch UI to disable SSR based on an ENV variable right?
> 2. You want to enable auth for every route in the server based on an ENV variable right?

You are correct on both fronts. 

For the enabling auth please, check out how we are curent doing `LoggedUser` middleware and make a new struct w/ the middleware trait implemented that you then include in the payload of all requests that do not currently have `LoggedUser` or have `Option<LoggedUser>`.

**Comment by ogil7190** [comment]
@skeptrunedev i am not able to run it on my system, is there any way to run it with minimal setup like redis and postgres without installing it locally ??

**Comment by skeptrunedev** [comment]
> @skeptrunedev i am not able to run it on my system, is there any way to run it with minimal setup like redis and postgres without installing it locally ??

The guide in the README should be fairly easy to follow and also work. 

Maybe the issue is that you did not set your OPENAI api key in the `.env`? 

If not, would you mind sharing where you got stuck?

**Comment by dfordp** [comment]
you could just add a middleware for and check at root layout file whether the user is authenticated

**Comment by skeptrunedev** [comment]
> you could just add a middleware for and check at root layout file whether the user is authenticated

That is the idea for `server`, yeah. Auth is not happening on the `layout` files for Astro/`search`
