### ISSUE TITLE
bugfix: hide show more button on ScoreCard and CardMetadataDisplay until after hydration

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#455]
### Description

For the `search` UI, there is currently a bug where if you expand a card before the client hydrates it, the card will become collapsed again after hydration goes through. 

![client-hydration-bug](https://github.com/arguflow/arguflow/assets/15804464/8d7f476e-0abb-45db-b5f1-8db51107f380)

The fix for this is not allowing the user to expand before hydration occurs by not showing the button if `window` is undefined. 

### Target(s)

`search`

### Requirement to close

- [ ] the "show more" button does not show until after the card component has been hydrated for both `ScoreCard.tsx` and `CardMetadataDisplay.tsx`

### PR commit requirements for a bounty claim

This PR should have only one commit titled as below.

- [ ] bugfix: hide show more button on ScoreCard and CardMetadataDisplay until after hydration

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by rishi-raj-jain** [comment]
@skeptrunedev Can you help me add a card locally? Even if I add 70 words it returns 400

**Comment by rishi-raj-jain** [comment]
https://github.com/arguflow/arguflow/assets/46300090/ce05e617-54b3-459a-a8f8-c666b5066e30

**Comment by skeptrunedev** [comment]
> @skeptrunedev Can you help me add a card locally? Even if I add 70 words it returns 400

Agh, making an issue. Will fix this right now.

**Comment by skeptrunedev** [comment]
> Screen.Recording.2023-09-22.at.9.06.08.AM.mov

Added to README. You have to install the node deps. We use node to get the raw content out of the html sent on the `create card` request payload. 

[Install node requirements](https://github.com/arguflow/arguflow#install-node-requirements)
yarn --cwd ./server/server-nodejs

**Comment by skeptrunedev** [comment]
https://github.com/arguflow/arguflow/pull/459

**Comment by rishi-raj-jain** [comment]
@skeptrunedev Still countering the error

**Comment by rishi-raj-jain** [comment]
So what I did is:

`rustup default nightly`
`pip install -r ./vault-python/requirements.txt`
`yarn --cwd ./server/server-nodejs`
cp .env.chat ./chat/.env
cp .env.search ./search/.env
cp ./server/.env.dist ./server/.env
./convenience.sh -l

then

terminal 1
cd server
cargo watch -x run

terminal 2
cd search
yarn
yarn dev

**Comment by rishi-raj-jain** [comment]
https://github.com/arguflow/arguflow/assets/46300090/01a3607e-30b1-4827-9346-9fb0a0561481

**Comment by rishi-raj-jain** [comment]
Are you sure you're not bug testing with me 😆

**Comment by skeptrunedev** [comment]
Ah shoot, so I just renamed `./server/vault-nodejs` to `./server/server-nodejs` . 

Everything else looks right. Either try `yarn --cwd ./server/vault-nodejs` or rebase and do `yarn --cwd ./server/server-nodejs`.

**Comment by skeptrunedev** [comment]
> Are you sure you're not bug testing with me 😆

Added $5 to the bounty. Sorry we did not do a good job documenting this.

**Comment by rishi-raj-jain** [comment]
> Ah shoot, so I just renamed ./server/vault-nodejs to ./server/server-nodejs .

Oh okay okay...

**Comment by rishi-raj-jain** [comment]
> Everything else looks right. Either try yarn --cwd ./server/vault-nodejs or rebase and do yarn --cwd ./server/server-nodejs.

Wait making another one from the latest directly, I see more commits

**Comment by rishi-raj-jain** [comment]
> Added $5 to the bounty. Sorry we did not do a good job documenting this.

Appreciate it! No worries, create another bounty and some magician will come in and make things hassle free for you xD

**Comment by rishi-raj-jain** [comment]
@skeptrunedev 

Can we hop on a meet? Please find attached. This is still giving me 400.

https://github.com/arguflow/arguflow/assets/46300090/dd762594-792c-48fd-aa5d-51a8ffb50d6d

**Comment by rishi-raj-jain** [comment]
Is this because of this env that you have?

<img width="603" alt="Screenshot 2023-09-22 at 10 07 00 AM" src="https://github.com/arguflow/arguflow/assets/46300090/811bac38-a829-4198-828a-30e8bb6ed000">

**Comment by skeptrunedev** [comment]
> @skeptrunedev
> 
> Can we hop on a meet? Please find attached. This is still giving me 400.
> 
>  Screen.Recording.2023-09-22.at.10.02.22.AM.mp4 
> Steps I did
> 
> create a new branch from the upstream: https://github.com/rishi-raj-jain/arguflow/tree/fix-bugfix-1
> 
> rustup default nightly pip install -r ./server/server-python/requirements.txt yarn --cwd ./server/server-nodejs cp .env.chat ./chat/.env cp .env.search ./search/.env cp ./server/.env.dist ./server/.env ./convenience.sh -l
> 
> then
> 
> terminal 1 cd server cargo watch -x run
> 
> terminal 2 cd search yarn yarn dev



> @skeptrunedev
> 
> Can we hop on a meet? Please find attached. This is still giving me 400.
> 
>  Screen.Recording.2023-09-22.at.10.02.22.AM.mp4 
> Steps I did
> 
> create a new branch from the upstream: https://github.com/rishi-raj-jain/arguflow/tree/fix-bugfix-1
> 
> rustup default nightly pip install -r ./server/server-python/requirements.txt yarn --cwd ./server/server-nodejs cp .env.chat ./chat/.env cp .env.search ./search/.env cp ./server/.env.dist ./server/.env ./convenience.sh -l
> 
> then
> 
> terminal 1 cd server cargo watch -x run
> 
> terminal 2 cd search yarn yarn dev

Sure - To join the video meeting, click this link: https://meet.google.com/rvc-ddfm-iec
Otherwise, to join by phone, dial +1 502-382-4130 and enter this PIN: 681 958 586#
To view more phone numbers, click this link: https://tel.meet/rvc-ddfm-iec?hs=5
