### ISSUE TITLE
feature: feeling lucky button 

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#465]
### Description

Allow the developer to pass in a csv of strings to a .env such that a user can hover over the "I'm feeling lucky" button and press it to make a random default search query. 

### Target(s)

`search`

### Requirement to close

- [ ] list of get lucky strings separated by commas are set in .env
- [ ] `SearchForm.tsx` picks up get lucky strings from .env
- [ ] add a button to `SearchForm.tsx` next to the `Create Evidence Card` button for `I'm feeling lucky`
- [ ] when user hovers over the "I'm feeling lucky button" text should scroll to the options present in the `.env` list and settle on 1 (reference google.com for this)
- [ ] "I'm feeling lucky button" has an animation if it expands horizontally so it looks smooth 
- [ ] when user presses "I'm feeling lucky button" it should cause a search to occur with the value that the scroll stopped on (reference google.com for this)

### PR commit requirements for a bounty claim

1 commit with the following message: 

"feature: feeling lucky button"

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
The button should go here and cause the row to shift left so everything stays justified on the center: 

![image](https://github.com/arguflow/arguflow/assets/15804464/18f608c2-88b0-4b9d-87bb-e14a778e83b7)

**Comment by rishi-raj-jain** [comment]
@skeptrunedev Which scroll do you mean on google.com?

**Comment by rishi-raj-jain** [comment]
https://github.com/arguflow/arguflow/assets/46300090/077377da-3d61-4fbe-b8da-f91e82720d2a

**Comment by skeptrunedev** [comment]
> @skeptrunedev Which scroll do you mean on google.com?

When you hover over the feeling lucky button on google, the text will scroll within the button. That's what I am referring to.

**Comment by rishi-raj-jain** [comment]
I attached a video above, can you check?

**Comment by skeptrunedev** [comment]
> I attached a video above, can you check?

Damn, we have different interfaces. On mobile, let me find a gif.

Here's a fairly good example: https://codepen.io/jwern/pen/VwmNavq

**Comment by rishi-raj-jain** [comment]
Awesome, thanks for the reference! Didn't know everyone but me sees it!

**Comment by rishi-raj-jain** [comment]
>  "I'm feeling lucky button" has an animation if it expands horizontally so it looks smooth

What do you mean by if it expands?

**Comment by skeptrunedev** [comment]
> > "I'm feeling lucky button" has an animation if it expands horizontally so it looks smooth
> 
> What do you mean by if it expands?

If it settles onto an 8 word string after spinning but starts on a 3 word one before spinning then it will get wider. When that happens, there should be an animation so it looks smooth.

**Comment by rishi-raj-jain** [comment]
Ahhh I see

**Comment by rishi-raj-jain** [comment]
Cool thanks, I'm on it!
