### ISSUE TITLE
feature: include dataset name with the title name

### ISSUE THREAD

**Issue by fastfists** [arguflow/arguflow#503]
### Description

Include dataset name with the title name
![image](https://github.com/arguflow/arguflow/assets/32852291/c9dc7820-d62c-461a-8c09-e05a665b5099)

### Target(s)

Arguflow search and Arguflow chat

### Requirement to close

Modify title to Arguflow Search - Dataset / Arguflow Chat - Dataset or whatever seems reasonable for pages that have alternative Title pages

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by rohit-singh-bisht** [comment]
@skeptrunedev Could you please assign this issue to me?

**Comment by skeptrunedev** [comment]
> @skeptrunedev Could you please assign this issue to me?

Assigned!

**Comment by rohit-singh-bisht** [comment]
@skeptrunedev Is there a live route for the pages? Or any particular file in the codebase?

**Comment by skeptrunedev** [comment]
> @skeptrunedev Is there a live route for the pages? Or any particular file in the codebase?

Do a grep across the repo for the meta tags
