### ISSUE TITLE
documentation: create a system diagram for Arguflow RAG

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#512]
### Description

@vtempest made a fairly good first draft at this - 
![image](https://github.com/arguflow/arguflow/assets/15804464/d74fee75-5201-4b23-9e79-c50a56fd7d6d) 

The goal of this PR to is to modify the diagram to better reflect the different pipeline between search and chat. For chat, the search query is used to generate a short completion that then becomes the final search query. This does not occur for search.

### Target(s)

N/A - this change will go on docs.arguflow.ai

### Requirement to close

- [ ] content: submit an updated diagram in the comments of this issue

### PR commit requirements for a bounty claim

No PR required.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by vid277** [comment]
I'll claim this.

**Comment by skeptrunedev** [comment]
Completed by @vid277
