### ISSUE TITLE
documentation: update docs for card creation

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#513]
### Description

On [docs.arguflow.ai](https://docs.arguflow.ai), the [card creation](https://docs.arguflow.ai/card#create-a-card) request documentation is out of date. We have since changed the request payload definition as per the [following code here](https://github.com/arguflow/arguflow/blob/main/server/src/handlers/card_handler.rs#L92)

### Target(s)

These changes will not be in this repository, but rather the [docs repo](https://github.com/arguflow/documentation).

`documentation`

### Requirement to close

- [ ] Merged PR on the [docs repo](https://github.com/arguflow/documentation) with updated docs for the card creation route

### PR commit requirements

1 commit with a message of `update: updated docs for the card creation route`. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by evelinabe** [comment]
Hi! Please assign this issue to me :)

**Comment by skeptrunedev** [comment]
> Hi! Please assign this issue to me :)

Sure! Assigned! 🚀

Don't forget to star the repo if you like the project 🌟❤️.

**Comment by evelinabe** [comment]
@skeptrunedev  Noticed that the README in the docs repo needs an update on the getting started section. It says to run `npm install` but there's a `yarn.lock` file in the repo. It should say something like run `yarn`, or if you prefer to use npm as package manager, delete the `yarn.lock`file before running `npm install`. That should be a new issue, though.

**Comment by skeptrunedev** [comment]
> @skeptrunedev  Noticed that the README in the docs repo needs an update on the getting started section. It says to run `npm install` but there's a `yarn.lock` file in the repo. It should say something like run `yarn`, or if you prefer to use npm as package manager, delete the `yarn.lock`file before running `npm install`. That should be a new issue, though.

100% agree. I'll make that

**Comment by skeptrunedev** [comment]
> @skeptrunedev Noticed that the README in the docs repo needs an update on the getting started section. It says to run `npm install` but there's a `yarn.lock` file in the repo. It should say something like run `yarn`, or if you prefer to use npm as package manager, delete the `yarn.lock`file before running `npm install`. That should be a new issue, though.

I just read through the README and the `npm install` is just `npm install -g yarn` so you can get `yarn` CLI if you did not previously have it. We won't actually need a new issue to fix this now. I appreciate the callout though.

**Comment by evelinabe** [comment]
> > @skeptrunedev Noticed that the README in the docs repo needs an update on the getting started section. It says to run `npm install` but there's a `yarn.lock` file in the repo. It should say something like run `yarn`, or if you prefer to use npm as package manager, delete the `yarn.lock`file before running `npm install`. That should be a new issue, though.
> 
> I just read through the README and the `npm install` is just `npm install -g yarn` so you can get `yarn` CLI if you did not previously have it. We won't actually need a new issue to fix this now. I appreciate the callout though.

Are you sure? I ended up with duplicate lock-files when I ran it.

**Comment by skeptrunedev** [comment]
> > > @skeptrunedev Noticed that the README in the docs repo needs an update on the getting started section. It says to run `npm install` but there's a `yarn.lock` file in the repo. It should say something like run `yarn`, or if you prefer to use npm as package manager, delete the `yarn.lock`file before running `npm install`. That should be a new issue, though.
> > 
> > 
> > I just read through the README and the `npm install` is just `npm install -g yarn` so you can get `yarn` CLI if you did not previously have it. We won't actually need a new issue to fix this now. I appreciate the callout though.
> 
> Are you sure? I ended up with duplicate lock-files when I ran it.

Yeah. I am definitely sure. I think you must have ran a different command. `npm install -g yarn` will not make a new lockfile for sure.

**Comment by evelinabe** [comment]
> > > > @skeptrunedev Noticed that the README in the docs repo needs an update on the getting started section. It says to run `npm install` but there's a `yarn.lock` file in the repo. It should say something like run `yarn`, or if you prefer to use npm as package manager, delete the `yarn.lock`file before running `npm install`. That should be a new issue, though.
> > > 
> > > 
> > > I just read through the README and the `npm install` is just `npm install -g yarn` so you can get `yarn` CLI if you did not previously have it. We won't actually need a new issue to fix this now. I appreciate the callout though.
> > 
> > 
> > Are you sure? I ended up with duplicate lock-files when I ran it.
> 
> Yeah. I am definitely sure. I think you must have ran a different command. `npm install -g yarn` will not make a new lockfile for sure.

I just followed this README https://github.com/arguflow/documentation#getting-started

**Comment by skeptrunedev** [comment]
> > > > > @skeptrunedev Noticed that the README in the docs repo needs an update on the getting started section. It says to run `npm install` but there's a `yarn.lock` file in the repo. It should say something like run `yarn`, or if you prefer to use npm as package manager, delete the `yarn.lock`file before running `npm install`. That should be a new issue, though.
> > > > 
> > > > 
> > > > I just read through the README and the `npm install` is just `npm install -g yarn` so you can get `yarn` CLI if you did not previously have it. We won't actually need a new issue to fix this now. I appreciate the callout though.
> > > 
> > > 
> > > Are you sure? I ended up with duplicate lock-files when I ran it.
> > 
> > 
> > Yeah. I am definitely sure. I think you must have ran a different command. `npm install -g yarn` will not make a new lockfile for sure.
> 
> I just followed this README https://github.com/arguflow/documentation#getting-started

I think the NVM step might be incomplete if anything

**Comment by evelinabe** [comment]
"I think the NVM step might be incomplete if anything"

Yeah, but that's in the README for the other repo. Seems like we are not talking about the same README here 😂

**Comment by skeptrunedev** [comment]
> @skeptrunedev "I think the NVM step might be incomplete if anything"
> 
> Yeah, but that's in the README for the other repo. Seems like we are not on the same page here 😂

Ohhhhhhhh! You are talking about for `arguflow/documentation` ? That makes so much more sense! Ok, yeah. That may for sure be wrong.

**Comment by skeptrunedev** [comment]
> @skeptrunedev "I think the NVM step might be incomplete if anything"
> 
> Yeah, but that's in the README for the other repo. Seems like we are not on the same page here 😂

Made that change! Thanks for the callout

**Comment by skeptrunedev** [comment]
This has been completed
