### ISSUE TITLE
documentation: update docs for filtering

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#514]
### Description

There are a few places on [docs.arguflow.ai](https://docs.arguflow.ai) where the filtering pieces are out of date: 

- https://docs.arguflow.ai/card#semantically-search-for-a-card
- https://docs.arguflow.ai/card#search-for-a-card-using-full-text
- https://docs.arguflow.ai/card_collection#search-semantically-within-a-collection
- https://docs.arguflow.ai/card_collection#search-a-collection-using-full-text

The updated filter payload is written in the codebase for `server` [here]https://github.com/arguflow/arguflow/blob/main/server/src/handlers/card_handler.rs#L553). 

### Target(s)

The PR to close this should be on [arguflow/documentation](https://github.com/arguflow/documentation). 

`documentation`

### Requirement to close

- [ ] PR on [arguflow/documentation](https://github.com/arguflow/documentation) updating filter payload in the places described above

### PR commit requirements for a bounty claim

N/A

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by Chetax** [comment]
@skeptrunedev  I Want to Work on this issue please assign it to me

**Comment by skeptrunedev** [comment]
> @skeptrunedev I Want to Work on this issue please assign it to me

I just assigned #537 to you. Once that issue is closed, I will be happy to assign this one to you. Also, I can swap out the assignment from #537 to this issue if you would prefer that.

**Comment by Chetax** [comment]
Ok Sir ,I am Starting Working on Issue #537 first .

**Comment by Chetax** [comment]
@skeptrunedev Sir my 537 pr merged now I want to work on this issue please  assign to me

**Comment by skeptrunedev** [comment]
> @skeptrunedev Sir my  issue #537 pr merged now I want to work on this issue please  assign to me

Assigning!

**Comment by vid277** [comment]
Hi, can I work on this?

**Comment by skeptrunedev** [comment]
This has been completed
