### ISSUE TITLE
documentation: add contributing guidelines 

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#520]
### Description

Add contributing guidelines so we are setup for hacktoberfest. 

### Target(s)

N/A - this will go in the root

### Requirement to close

Contributing guidelines added to repo. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by ShatilKhan** [comment]
Can you please assign this to me?
I've done docs contributions before

**Comment by skeptrunedev** [comment]
> Can you please assign this to me? I've done docs contributions before

Assigned! The help is much appreciated! 

![image](https://github.com/arguflow/arguflow/assets/15804464/bd17991d-61b1-4979-8f7e-ef249e12c792)

**Comment by ShatilKhan** [comment]
You got a ⭐ from me!

**Comment by skeptrunedev** [comment]
Hey @ShatilKhan I just finished adding these so I am closing the issue. I am sorry for stepping on your toes here, but I really wanted to make sure we had everything needed to participate in hacktober before it starts in a couple hours. 

We welcome any future contributions!
