### ISSUE TITLE
bugfix: mobile UI is messed up due to github star button

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#521]
### Description

On a phone it looks like the below. The solution is to hide the Arguflow logo at a larger width. 

![Screenshot_20230929-165952~2](https://github.com/arguflow/arguflow/assets/15804464/5b5d6666-cf77-47f4-b9d6-7239bf5b5c70)

### Target(s)

`search`

### Requirement to close

Merged PR that hides the Arguflow logo at a larger width. 

### PR commit requirements for a bounty claim

1 commit, `bugfix: mobile UI is messed up due to github star button`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by soykot2910** [comment]
Hi @skeptrunedev, I'd like to work on this issue. Could you please assign this issue to me?

**Comment by skeptrunedev** [comment]
> Hi @skeptrunedev, I'd like to work on this issue. Could you please assign this issue to me?

Most definitely! Assigned!

**Comment by rohit-singh-bisht** [comment]
Hello, @skeptrunedev 

Could you kindly assign the issue to me? Additionally, could you please reiterate the solution? The issue description suggests hiding the Arguflow logo at a wider screen width.

**Comment by skeptrunedev** [comment]
> Hello, @skeptrunedev
> 
> Could you kindly assign the issue to me? Additionally, could you please reiterate the solution? The issue description suggests hiding the Arguflow logo at a wider screen width.

Assigned! Please do star the repo if you like the projct :heart: :star: ! More details on the issue below.

In the file below with the highlighted path we are hiding the logo unless the width is at least `360px`. We need to increase the `360` value to something larger such that it does not cause this layout break. 

![image](https://github.com/arguflow/arguflow/assets/15804464/e9ce61c7-4dce-49d7-9d07-54477e3f79ae)

**Comment by skeptrunedev** [comment]
> Hi @skeptrunedev, I'd like to work on this issue. Could you please assign this issue to me?

Are you still working on this issue? I unassigned for now assuming not, but would like to make sure.

**Comment by skeptrunedev** [comment]
Hey @soykot2910 and @rohit-singh-bisht :wave: . 

I am closing this because it got solved in #559 by @poke5352 !
