### ISSUE TITLE
bugfix: when you create a new collection on a card, it should add that option to all cards' popovers

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#522]
### Description

When you create a collection using the bookmarks popover on a card, it does not bubble up to other cards. We need to make it bubble up. 

![collection-creation-does-not-bubble-up](https://github.com/arguflow/arguflow/assets/15804464/3726ee7b-9e69-46c2-ae6a-bd4a3263c87e)

### Target(s)

`search`

### Requirement to close

Merged PR that makes created collections bubble up to the rest of the cards. 

### PR commit requirements for a bounty claim

1 commit with the message: `bugfix: card collections should bubble up after creation`. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by rohit-singh-bisht** [comment]
Hi @skeptrunedev I'd like to work on this issue. Could you please assign this issue to me?

**Comment by skeptrunedev** [comment]
> Hi @skeptrunedev I'd like to work on this issue. Could you please assign this issue to me?

Yes! Assigned now!

Don't forget to star the repo! :heart: 

![image](https://github.com/arguflow/arguflow/assets/15804464/ed199ebf-72dd-478d-a74c-1738349eaa81)
