### ISSUE TITLE
feature: allow for a `.env` variable that controls the lines available before `show more`

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#523]
### Description

Depending on the deployment, you may want more or less lines to show before `show more`. 

### Target(s)

`search`,`chat`

### Requirement to close

Merged PR that makes the lines before `show more` settable via a `.env` var.

### PR commit requirements for a bounty claim

1 commit with the following message: `feature: allow for a `.env` variable that controls the lines available before `show more``

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by Scorpil** [comment]
I can take a stab at this.
