### ISSUE TITLE
feature: make the opengraph tags set via a .env

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#526]
### Description

Currently the opengraph tags for `search` are hardcoded. We want to make it such that they can be set via the `.env`. This would allow us to have accurate opengraph tags for multiple datasets. 

### Target(s)

`search`

### Requirement to close

- [ ] merged PR that allows for the opengraph tags to be set via `.env`

### PR commit requirements for a bounty claim

1 commit with the message `feature: make the opengraph tags set via a .env`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
The outlined code below needs to be set via a .env as highlighted or changed as written

![image](https://github.com/arguflow/arguflow/assets/15804464/d0bdbb28-1f8d-4494-8bfe-aa8572046796)

![image](https://github.com/arguflow/arguflow/assets/15804464/8aaf7781-a210-4415-a7a0-d5c1de72a551)

![image](https://github.com/arguflow/arguflow/assets/15804464/52828195-e3bd-4546-8497-dfce29d23b09)

**Comment by Dv04** [comment]
I would like to work on this.

**Comment by skeptrunedev** [comment]
> I would like to work on this. If you can assign me. I will submit the PR by tomorrow as due to hacktoberfest.

Yes, assigning now!

**Comment by Dv04** [comment]
> Yes, assigning now!

Thanks. Will update as soon as done

**Comment by Dv04** [comment]
Hey @skeptrunedev I have created a pull request for this issue. PLease have a look.

[#546](https://github.com/arguflow/arguflow/pull/546)
