### ISSUE TITLE
bugfix: remove forever spinning loading circle from `search` UI

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#527]
### Description

For some reason there is a loading spinner that never stops on the `search` settings page. 

![image](https://github.com/arguflow/arguflow/assets/15804464/d738807c-5416-45f8-ae33-f8a40461b3e2)

### Target(s)

`search`

### Requirement to close

- [ ] PR with example video showing that the perpetual spinner in the settings is removed

### PR commit requirements for a bounty claim

1 commit with the message: `bugfix: remove forever spinning loading circle from search UI`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by bharath090909** [comment]
@Skeptrunedev, I'm keen to step up and take on this challenge. Can I take up on this issue?

**Comment by skeptrunedev** [comment]
> @skeptrunedev, I'm keen to step up and take on this challenge. Can I take up on this issue?

Have at it! 

And don't forget to star :heart: 

![image](https://github.com/arguflow/arguflow/assets/15804464/94ac93e0-097d-468a-b7ee-6dc3445d5a87)
