### ISSUE TITLE
documentation: modify the quickstart authentication details to include API key

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#530]
### Description

In #437 we added support for API key based authentication. That is currently missing from [docs.arguflow.ai](https://docs.arguflow.ai). 

We would like to add it to our docs through a PR to [github.com/arguflow/arguflow](https://github.com/arguflow/arguflow). 

### Target(s)

[github.com/arguflow/arguflow](https://github.com/arguflow/arguflow)

### Requirement to close

- [ ] merged PR to [github.com/arguflow/arguflow](https://github.com/arguflow/arguflow) that adds docs on how to use API key 

### PR commit requirements for a bounty claim

1 commit with the message `documentation: modify the quickstart authentication details to include API key`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by soykot2910** [comment]
Hi @skeptrunedev, I'd like to work on this issue. Could you please assign this issue to me?

**Comment by skeptrunedev** [comment]
> Hi @skeptrunedev, I'd like to work on this issue. Could you please assign this issue to me?

I assigned the mobile UI bug to you just now. Happy to swap the assignment to this issue or assign this to you once the other one is complete.

**Comment by AvaterClasher** [comment]
Can i be assigned this ?

**Comment by skeptrunedev** [comment]
> Can i be assigned this ?

Sure! Assigned! Don't forget to star the repo if you think the project is cool :heart: . 

![image](https://github.com/arguflow/arguflow/assets/15804464/4acf5635-d223-4ced-9634-3023851b31a0)

**Comment by postmeback** [comment]
If the present assignee is unable to finish it, I would like to take it up.

**Comment by skeptrunedev** [comment]
> If the present assignee is unable to finish it, I would like to take it up.

Going to assign it to you right now! 

Also make sure to :star: if you haven't and like the project :rocket: !

**Comment by skeptrunedev** [comment]
This has been completed
