### ISSUE TITLE
feature: when you bookmark a recommended card while viewing collection move it into collection

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#531]
### Description

When you bookmark a recommended card into the collection you are currently viewing, that card should move into the collection. Imo, it should be added to the bottom of the page currently being used and removed from the recommended list.

![card-does-not-move-into-collection](https://github.com/arguflow/arguflow/assets/15804464/a1849937-5d17-4b15-8c3f-48588a9bf6d1)

### Target(s)

`search`

### Requirement to close

- [ ] merged PR which results in a card bookmarked while reviewing a collection being moved into that collection

### PR commit requirements for a bounty claim

1 commit with the message `feature: when you bookmark a recommended card while viewing collection move it into collection`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by NewtonFernandis** [comment]
Hi @skeptrunedev, Could you please assign this issue to me? I will work on this.

**Comment by skeptrunedev** [comment]
> Hi @skeptrunedev, Could you please assign this issue to me? I will work on this.

Sure! Looking forward to your PR :heart: . Make sure to star the repo! 

![image](https://github.com/arguflow/arguflow/assets/15804464/38670226-ba8c-45a4-9179-1d3be80c51ee)

**Comment by rohit-singh-bisht** [comment]
@skeptrunedev Could you please assign this issue to me?

**Comment by skeptrunedev** [comment]
> @skeptrunedev Could you please assign this issue to me?

Doing it now! Let us know if we can help you

**Comment by rohit-singh-bisht** [comment]
@skeptrunedev Could you please tell how to reproduce this related cards list? Any direct for it URL?

**Comment by rohit-singh-bisht** [comment]
@skeptrunedev 

> > @skeptrunedev Could you please tell how to reproduce this related cards list? Any direct URL for it?
> 
> Set the following as your env's for `search`.
> 
> ```
> PUBLIC_API_HOST=https://enron-api.arguflow.ai/api
> PLAUSIBLE_HOST=https://enron-search.arguflow.ai
> PUBLIC_FILTER_ITEMS="[]"
> PUBLIC_CREATE_EVIDENCE_FEATURE="on"
> PUBLIC_DOCUMENT_UPLOAD_FEATURE="on"
> PUBLIC_SEARCH_QUERIES="star github.com/arguflow/arguflow, no seriously please star github.com/arguflow/arguflow, you know you want to star github.com/arguflow/arguflow"
> PUBLIC_LUCKY_ITEMS="Good, Bad, Sad, Happy, Annoyed, Suspicious, Who Knows, Meh"
> PUBLIC_FRONTMATTER_VALS="Date,From,Subject,To"
> PUBLIC_LINES_BEFORE_SHOW_MORE=4
> PUBLIC_SHOW_GITHUB_STARS="on"
> GITHUB_TOKEN=github_pat_**********************************************************************************
> DATASET=foo
> OG_DESCRIPTION="Demo of Arguflow's best-in-class semantic search infrastructure for debate evidence."
> PUBLIC_ALWAYS_REQUIRE_AUTH="off"
> PUBLIC_IMAGE_RANGE_START_KEY=""
> PUBLIC_IMAGE_RANGE_END_KEY=""
> PUBLIC_DATE_RANGE_VALUE=""
> PUBLIC_FILTER_ITEMS="[]"
> SUGGESTED_QUERIES=""
> ```
> 
> Then you can navigate to a single card by pressing the external link icon to get those recommendations. To get the ones for a collection, you can create an account then put cards into a collection and navigate to the collection page by clicking the collection from your profile or the bookmark popover.

I updated the env. Now it is showing 401 unauthorised for auth.

**Comment by skeptrunedev** [comment]
> @skeptrunedev
> 
> > > @skeptrunedev Could you please tell how to reproduce this related cards list? Any direct URL for it?
> > 
> > 
> > Set the following as your env's for `search`.
> > ```
> > PUBLIC_API_HOST=https://enron-api.arguflow.ai/api
> > PLAUSIBLE_HOST=https://enron-search.arguflow.ai
> > PUBLIC_FILTER_ITEMS="[]"
> > PUBLIC_CREATE_EVIDENCE_FEATURE="on"
> > PUBLIC_DOCUMENT_UPLOAD_FEATURE="on"
> > PUBLIC_SEARCH_QUERIES="star github.com/arguflow/arguflow, no seriously please star github.com/arguflow/arguflow, you know you want to star github.com/arguflow/arguflow"
> > PUBLIC_LUCKY_ITEMS="Good, Bad, Sad, Happy, Annoyed, Suspicious, Who Knows, Meh"
> > PUBLIC_FRONTMATTER_VALS="Date,From,Subject,To"
> > PUBLIC_LINES_BEFORE_SHOW_MORE=4
> > PUBLIC_SHOW_GITHUB_STARS="on"
> > GITHUB_TOKEN=github_pat_**********************************************************************************
> > DATASET=foo
> > OG_DESCRIPTION="Demo of Arguflow's best-in-class semantic search infrastructure for debate evidence."
> > PUBLIC_ALWAYS_REQUIRE_AUTH="off"
> > PUBLIC_IMAGE_RANGE_START_KEY=""
> > PUBLIC_IMAGE_RANGE_END_KEY=""
> > PUBLIC_DATE_RANGE_VALUE=""
> > PUBLIC_FILTER_ITEMS="[]"
> > SUGGESTED_QUERIES=""
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Then you can navigate to a single card by pressing the external link icon to get those recommendations. To get the ones for a collection, you can create an account then put cards into a collection and navigate to the collection page by clicking the collection from your profile or the bookmark popover.
> 
> I updated the env. Now it is showing 401 unauthorised for auth.

Yep. That is what should happen. When a 401 response is returned for recommendations we want to run `setShowNeedLoginModal(true);` such that the `loginModal` is displayed.

**Comment by rohit-singh-bisht** [comment]
@skeptrunedev I created an account and attempted to log in, but the API response I received had a status code of 204 No Content.

**Comment by skeptrunedev** [comment]
> @skeptrunedev I created an account and attempted to log in, but the API response I received had a status code of 204 No Content. I tried to login multiple times in local but can't login.
> 
> Attached screen recording for reference: 
> https://github.com/arguflow/arguflow/assets/82527615/1efe266b-1562-415d-8040-c4c54f61636b
> 
> 

Ahhh, if you point local at a prod API then it cannot correctly set the cookie. The 204 is correct, but the set-cookie header isn't working.

The easiest way to work this issue is probably to just get the backend running locally with the steps in the README. From there you should be good to create cards and make collections so you can test.

**Comment by skeptrunedev** [comment]
There is a lot of layout shift when doing this and it isn't a priority, so closing as unplanned for now.
