### ISSUE TITLE
content: update the README discord shield to include discord member count

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#532]
### Description

Based on [this list of github badges for discord](https://naereen.github.io/badges/#discord) there should be a way to make our discord shield in the README contain the current member count. We would like to replace the current Discord shield with one that shows the member count.

![image](https://github.com/arguflow/arguflow/assets/15804464/3648fd0f-d717-4e97-b7af-0896e9053e49)

### Target(s)

the README of this repo

### Requirement to close

- [ ] merged PR that replaces the current discord shield with one that shows member count

### PR commit requirements for a bounty claim

1 commit with the following message: `content: update the README discord shield to include discord member count`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by Neel-07** [comment]
Hello @skeptrunedev, can you assign me this issue i want to work on this, I have already forked it and i think i can solve the issue

**Comment by skeptrunedev** [comment]
> Hello @skeptrunedev, can you assign me this issue i want to work on this, I have already forked it and i think i can solve the issue

Absolutely! Make sure to star! 🌟❤️

**Comment by Neel-07** [comment]
hello @skeptrunedev, wanted to ask something is the widget setting of the server is enabled ... 
coz 
<img width="608" alt="image" src="https://github.com/arguflow/arguflow/assets/112561276/33afcc1d-127d-48b7-95cf-80720bd31e7c">

**Comment by skeptrunedev** [comment]
> hello @skeptrunedev, wanted to ask something is the widget setting of the server is enabled ... coz <img alt="image" width="608" src="https://user-images.githubusercontent.com/112561276/271756867-33afcc1d-127d-48b7-95cf-80720bd31e7c.png">

Uhh, maybe not. Did not know that was a thing. Trying to fix now.

**Comment by skeptrunedev** [comment]
Should be on now!
