### ISSUE TITLE
documentation: add sudo apt install command to README guide

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#537]
### Description

When new contributors are coming to the repository, they are getting stuck by not quite understanding how to install the listed packages. We want to add `sudo apt install` to the beginning of the package list such that new contributors can follow how to do it. 

![image](https://github.com/arguflow/arguflow/assets/15804464/9f0b80b2-5c40-4912-9909-e02ede351e79)

### Target(s)

`README`

### Requirement to close

- [ ] merged PR that adds `sudo apt install` as a prefix to the package list

### PR commit requirements

1 commit with the message: `documentation: add sudo apt install command to README guide`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by Chetax** [comment]
I WAMT TO WORK ON THIS ISSUE CAN YOU PLEASE ASSIGN IT TO ME

**Comment by skeptrunedev** [comment]
> @skeptrunedev i want to work on this issue can you please assign it to me

Assigned! Also, please star the repo :heart: ! 

![image](https://github.com/arguflow/arguflow/assets/15804464/35231b60-a351-4ca3-bfcb-8b649f332ede)

**Comment by Chetax** [comment]
@skeptrunedev  sir can you please check my pr what is wrong in it. please

**Comment by AmeyaVerma** [comment]
https://github.com/skeptrunedev i can work on this, please assign me this

**Comment by skeptrunedev** [comment]
> https://github.com/skeptrunedev i can work on this, please assign me this

This issue was resolved in #540 but we appreciate you wanting to contribute! We will have more good first issues in the future, so please come back if you find the project interesting and star :heart: . 

![image](https://github.com/arguflow/arguflow/assets/15804464/958a5d7d-e056-4d65-8a05-58e30f32af71)
