### ISSUE TITLE
styling: make the scroll bar in dark mode be dark colors 

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#544]
### Description

Currently, for `search`, the scrollbar is not in dark mode when it should be. We would like to change this. [Here is an example from `chat` where it is correct](https://github.com/arguflow/arguflow/blob/main/chat/src/components/Atoms/AfMessage.tsx#L151). 

![image](https://github.com/arguflow/arguflow/assets/15804464/82bf3d54-f205-4ed0-b4ca-e31dda23262b)

### Target(s)

`search`

### Requirement to close

- [ ] merged PR that satisfies CI checks and makes the `search` scrollbar dark colors in dark mode

### PR commit requirements 

1 commit with a message of `styling: make the scroll bar in dark mode be dark colors `. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
> please assign me this issue

Assigned! Make sure to star the repo if you haven't yet :heart: ! 

![image](https://github.com/arguflow/arguflow/assets/15804464/1a9be3ba-de23-4656-8d9e-7c116924e091)

**Comment by Baburao-sanivada** [comment]
Can I Work On This?

**Comment by skeptrunedev** [comment]
> Can I Work On This?

Absolutely! Go right ahead. Excited for your contribution :rocket: ! 

![image](https://github.com/arguflow/arguflow/assets/15804464/9a0d454c-7026-43c5-894e-a65e14c78564)

**Comment by Basudeb2025** [comment]
please assign me this issue

**Comment by skeptrunedev** [comment]
> please assign me this issue

Assigned! Don't forget to star the repo if you think the project is doing something good :star: :heart: !

**Comment by Rehan52004** [comment]
is this issue open ?

**Comment by skeptrunedev** [comment]
> is this issue open ?

This is still open! Assigning you for now. 

Don't forget to star the repo if you like the project and haven't yet :star: :heart: !

**Comment by Rehan52004** [comment]
this change is related to only ui, so i have to setup all requirment as readme mention ?

**Comment by rohit-singh-bisht** [comment]
Hey @skeptrunedev.
Could you assign this issue to me?
I would like to work on this issue.
Please mention the browser and OS also.

**Comment by skeptrunedev** [comment]
> Hey @skeptrunedev.
> Could you assign this issue to me?
> I would like to work on this issue.
> Please mention the browser and OS also.

Will assign! And chrome on any OS.
