### ISSUE TITLE
documentation: add steps for getting the repo running locally in Windows to README

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#545]
### Description

We currently only support Linux as a development environment. We would like to expand this to support windows since many new contributors are using Windows. To that end, we need to figure out how to run everything on Windows and document it. 

You should likely be a somewhat experienced dev to work on this issue. 

### Target(s)

`README`

### Requirement to close

- [ ] merged PR that adds content to the README about how to run the repo in windows 

### PR commit requirements for a bounty claim

1 commit with a message of `documentation: add steps for getting the repo running locally in Windows to README`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by khushpreetsinghb** [comment]
I am new to open source, I can do this, please assign this to me.

**Comment by Ayush-Tibrewal** [comment]
@skeptrunedev  please assign me with this issue under hack October fest  i am UIUIX desiger and i will easily design it

**Comment by skeptrunedev** [comment]
> I am new to open source, I can do this, please assign this to me.

This is not a good issue for someone new to open source. I recommend taking an issue from this list of good first issues - https://github.com/arguflow/arguflow/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22 

Also, make sure to star the repo! :heart: :star:

**Comment by skeptrunedev** [comment]
> @skeptrunedev please assign me with this issue under hack October fest i am UIUIX desiger and i will easily design it

Hey Ayush! This issue will not require a design. While not quite we are looking for on this issue, you can apply your design skills to https://github.com/arguflow/arguflow/issues/511 if you would like! :heart: 

![image](https://github.com/arguflow/arguflow/assets/15804464/d8e628a3-905e-4478-9203-54700cb2deb4)

**Comment by poke5352** [comment]
Can you assign? I will try to get it working.
