### ISSUE TITLE
improvement: change service names in .env.server to be localhost

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#549]
### Description

![image](https://github.com/arguflow/arguflow/assets/15804464/a159c627-b8cf-4be7-a587-472f569724c8)

In the outlined boxes of the above image there are docker service names instead of localhost. We want to change those to be `localhost`. 

### Target(s)

`.env.server`

### Requirement to close

- [ ] merged PR that changes the outlined service names to `localhost`

### PR commit requirements

1 commit with a message of `improvement: change service names in .env.server to be localhost`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by ujwalkumar1995** [comment]
Hey @skeptrunedev 
I would like to work on this issue.
Could you please assign?

**Comment by ujwalkumar1995** [comment]
Hey @fastfists 
Would be happy to fix this. In the docker-compose file, API_HOST variable is used in the vault-search service. I did not quite get on what do we need to change here. Could you please elaborate?

**Comment by fastfists** [comment]
Yeah so API_HOST is not located in either .env.search or .env chat, they use PUBLIC _API_HOST and VITE_API_HOST respectively, should be easier to change that so it isn't too magical

**Comment by skeptrunedev** [comment]
Solved in #552
