### ISSUE TITLE
cleanup: rename collections to themes in UI

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#560]
### Description

Rename collections to themes in UI for `search`

### Target(s)

`search`

### Requirement to close

- [ ] merged PR that changes `collection` to `theme` in `search` UI

### PR commit requirements for a bounty claim

1 commit with a message of `cleanup: rename collections to themes in UI`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by HeetVekariya** [comment]
I would like to work on this issue.
Can you give the location to the file that need change.
Also if I can get more information it would be helpful.

**Comment by Zyzer01** [comment]
Hey there!
I'd love to work on this issue, Kindly assign to me

**Comment by skeptrunedev** [comment]
Hey @Zyzer01 and @HeetVekariya 

You need to change `collection` to theme everywhere that `collection` appears in the UI. There are many files in `search` that end in `.tsx` which have this. I trust that you will be able to figure out which files those are and where in them. 

If I go through that process then I may as well just complete the ticket :sweat_smile: . 

Make sure to star the repo if you like the project and haven't yet! :star: :heart:
