### ISSUE TITLE
bugfix: the logo of the twiiter is not updated

### ISSUE THREAD

**Issue by Rohit-Sharmaa** [arguflow/arguflow#562]
### Description

The logo of the twitter is old logo of twitter , it should be updated.

### Target(s)

Replace the old logo of twitter with new logo of twitter. 

This issue needs to be closed through a PR on the [landing](https://github.com/arguflow/landing) repository.

### Requirement to close

just update the new old logo with new logo of twitter

Screenshot
<img width="919" alt="Screenshot 2023-10-04 152612" src="https://github.com/arguflow/arguflow/assets/130988755/af43566f-e33d-4920-b05f-5b221788562a">

**Comment by HeetVekariya** [comment]
I can also do this after completing first an issue assigned to me

**Comment by Rjchauhan18** [comment]
I would also like to work on this issue. @HeetVekariya as i am new to open source and i find this issue as good first issue, so can you please left this issue to me. 
Also, @skeptrunedev  Can you please add the HacktoberFest label to this issue.

**Comment by HeetVekariya** [comment]
Okay, @Rjchauhan18 go for it. 👍

**Comment by densumesh** [comment]
> * I would also like to work on this issue.
> * @HeetVekariya as i am new to open source and i find this issue as good first issue, so can you please left this issue to me.
> * Also, @skeptrunedev  Can you please add the **HacktoberFest** label to this issue.
> * I have made the solution for the isuue:
>   ![image](https://user-images.githubusercontent.com/113838908/272780742-3598d212-bf4f-49d0-878a-03c03a0de5ef.png)

Assigned!

**Comment by Rjchauhan18** [comment]
I want to submit the PR for this, would it be accepted for HacktoberFest if it doesn't have hacktoberfest label.

**Comment by skeptrunedev** [comment]
> I want to submit the PR for this, would it be accepted for HacktoberFest if it doesn't have hacktoberfest label.

Yes! Added the hacktober label :)

**Comment by skeptrunedev** [comment]
> > I want to submit the PR for this, would it be accepted for HacktoberFest if it doesn't have hacktoberfest label.
> 
> Yes! Added the hacktober label :)


Make sure to star the repo if you haven't and like the project! :star: :heart:

**Comment by Rjchauhan18** [comment]
Hello, @skeptrunedev  

I have fixed the issue https://github.com/arguflow/arguflow/issues/562 and generated PR in `arguflow / landing` repository

**Comment by skeptrunedev** [comment]
> Hello, @skeptrunedev
> 
> I have fixed the issue #562 and generated PR in `arguflow / landing` repository
> 
> Could you please check ✅ it ?
> 
> And also please register `arguflow / landing` repository in hectoberfest so it can count in event.

Merged! I also did the necessary steps to enroll `landing` in hacktober so you should receive credit.

**Comment by Rjchauhan18** [comment]
Thank you so much @skeptrunedev
