### ISSUE TITLE
bugfix: when you are not auth'ed and get a 401 on the single card recommendations, it should show

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#588]
### Description

The user should get a modal telling them to sign in here and also on the collection page. 

![image](https://github.com/arguflow/arguflow/assets/15804464/af6e8ee2-ab52-49ff-8cd0-42794f424bf0)

### Target(s)

`search`

### Requirement to close

- [ ] merged PR that adds a modal telling the user to sign in if they get a 401 on the recommend for a single card or collection

### PR commit requirements for a bounty claim

1 commit with a message of `bugfix: when you are not auth'ed and get a 401 on the single card recommendations, it should show`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by rohit-singh-bisht** [comment]
@skeptrunedev 
Could you please assign this issue to me? Is there any modal component or UI for the same?

**Comment by skeptrunedev** [comment]
> @skeptrunedev Could you please assign this issue to me? Is there any modal component or UI for the same?

The modal is triggered via running setShowNeedLoginModal(true); such that the loginModal is displayed.

If you do a ctrl-shift-f to search the codebase, you should be able to find it.
