### ISSUE TITLE
feature: implement Google OAuth 2.0

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#591]
### Description

User's have requested the ability to sign in via Google. We would like to support this if possible, however, it is not a priority of maintainers. 

### Target(s)

`search`,`chat`,`server`

### Requirement to close

- [ ] users can sign in via Google from the `/auth/login` route for `search`
- [ ] users can sign in via Google from the `/auth/login` route for `chat`
- [ ] if user's Google email is already registered for an account, connect it to the existing account
- [ ] if user's Google email is not connected to an account, create a new account
- [ ] allow for disabling of Google auth via `env` for `search`, `chat`, and `server`

### PR commit requirements

As many commits as make sense here. Tagged appropriately. General guideline would be one tagged `feature: ` colon with a message tying to every checkbox in the "requirements to close" section. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by vtempest** [comment]
I have taken this issue and will finish to tomorrow with Google One Tap

**Comment by skeptrunedev** [comment]
I think we should really just migrate to an authentication microservice instead of having this be something included in `server`

**Comment by skeptrunedev** [comment]
We plan to add this with keycloak
