### ISSUE TITLE
feature: chatbox modal for search UI 

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#596]
### Description

User should be able to check off cards and then open a modal to chat w/ them. 

The modal should let them select all and then also unselect everything currently selected. 

### Target(s)

`search`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by vtempest** [comment]
This can also have suggested things like actions on a card to help the user know what to prompt. example prompt can be like "write a one sentence summary of the key bullet points"
