### ISSUE TITLE
feature: search history

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#600]
### Description

Use localstorage to store a user's search history and display it as below: 

![image](https://github.com/arguflow/arguflow/assets/15804464/f33831de-86d7-4b60-9606-e21553ec7379)

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by rohitmondal03** [comment]
@skeptrunedev can you assign me this issue !!

**Comment by skeptrunedev** [comment]
> @skeptrunedev can you assign me this issue !!

Sure, assigned!

**Comment by rohitmondal03** [comment]
Can you please explain like how to reproduce this issue/bug in the website ??

**Comment by rohit-singh-bisht** [comment]
Hi @skeptrunedev,
Could you please assign this issue to me?

I've implemented the feature: search history. Could you take a look at the attached video and confirm if it meets your expectations? If there are any changes you'd like me to make before proceeding, please let me know.

https://github.com/arguflow/arguflow/assets/82527615/3b39eeeb-1cc9-487a-a073-9773b1707404

**Comment by skeptrunedev** [comment]
> Hi @skeptrunedev, Could you please assign this issue to me?
> 
> I've implemented the feature: search history. Could you take a look at the attached video and confirm if it meets your expectations? If there are any changes you'd like me to make before proceeding, please let me know.
> 
>  Screen.Recording.2023-10-20.at.9.19.41.PM.mp4

That looks perfect!!! 

You are a hero man!!! 

Seriously, amazing work!!

**Comment by skeptrunedev** [comment]
> Hi @skeptrunedev, Could you please assign this issue to me?
> 
> I've implemented the feature: search history. Could you take a look at the attached video and confirm if it meets your expectations? If there are any changes you'd like me to make before proceeding, please let me know.
> 
>  Screen.Recording.2023-10-20.at.9.19.41.PM.mp4

Please do put the PR up and I will review and get that merged ASAP

**Comment by skeptrunedev** [comment]
> Hi @skeptrunedev, Could you please assign this issue to me?
> 
> I've implemented the feature: search history. Could you take a look at the attached video and confirm if it meets your expectations? If there are any changes you'd like me to make before proceeding, please let me know.
> 
>  Screen.Recording.2023-10-20.at.9.19.41.PM.mp4
