### ISSUE TITLE
bugfix: docs sidebar scroll was not working

### ISSUE THREAD

**Issue by vtempest** [arguflow/arguflow#601]
### Description

https://docs.arguflow.ai/
Sidebar won't scroll so you cannot see bottom content on smaller laptops.

### Target(s)

`docs` - https://github.com/arguflow/documentation

### Requirement to close

Allow for scrolling on sidebar of docs

### PR commit requirements

1 commit with a message of `bugfix: docs sidebar scroll was not working`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by mjubair** [comment]
@skeptrunedev I have raised a PR with the fix for this issue. Please review, hope this meets your requirement https://github.com/arguflow/documentation/pull/53

**Comment by skeptrunedev** [comment]
Thank you for closing this in https://github.com/arguflow/documentation/pull/53 @mjubair !!! 

Please make sure to star the repo if you like the project and haven't yet! :heart: 

cc: @vtempest @Preetraj2002

**Comment by mjubair** [comment]
@skeptrunedev Thanks for the approval. I have already started the repo.
