### ISSUE TITLE
Navbar UI and Side Button Improvement ✨

### ISSUE THREAD

**Issue by amanjaiman1** [arguflow/arguflow#619]
### Description

In this website, Navbar UI improvement should be welcome, and also a side Button i.e. "Star us"

Please label as fast and assign me this issue so i start working on it because hactoberfest deadline is tomorrow

### Target(s)

<replace w/ one or more of the following options: `server`, `search`, `chat`>

### Requirement to close

<please describe what is required to close this issue here>

### PR commit requirements for a bounty claim

<N/A if not a bounty PR; otherwise please describe the number of commits expected and messages expected >

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
What do you want to change with this issue?
