### ISSUE TITLE
Discord and Telegram Links don't go anywhere.

### ISSUE THREAD

**Issue by Keith-Web3** [arguflow/arguflow#621]
### Description

I noticed the telegram and discord links on at the bottom of the homepage don't go anywhere. Are there no telegram and discord channels yet or was it an oversight?

### Requirement to close

Add the appropriate links for discord and telegram.

### PR commit requirements for a bounty claim
N/A

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
> ### Description
> I noticed the telegram and discord links on at the bottom of the homepage don't go anywhere. Are there no telegram and discord channels yet or was it an oversight?
> 
> ### Requirement to close
> Add the appropriate links for discord and telegram.
> 
> ### PR commit requirements for a bounty claim
> N/A
> 
> ### Community channels
> Matrix is preferred. Reach out on discord or Matrix for further assistance.
> 
> * [discord](https://discord.gg/CuJVfgZf54)
> * [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

This is an oversight. Will take a look and fix today.

**Comment by Keith-Web3** [comment]
Alright 👍

**Comment by skeptrunedev** [comment]
This is now fixex
