### ISSUE TITLE
Issue when setting up dev environment

### ISSUE THREAD

**Issue by liebkne** [arguflow/arguflow#622]
### Description

Got 

```
[2023-11-01T10:05:14Z ERROR r2d2] connection to server at "db" (198.18.1.45), port 5432 failed: server closed the connection unexpectedly
    	This probably means the server terminated abnormally
    	before or while processing the request.
    
[2023-11-01T10:05:19Z ERROR r2d2] connection to server at "db" (198.18.1.45), port 5432 failed: server closed the connection unexpectedly
    	This probably means the server terminated abnormally
    	before or while processing the request.
```

when following instructions [here](https://github.com/arguflow/arguflow#local-development-with-linux). Everything is fine until [this](https://github.com/arguflow/arguflow#install-cargo-watch) step.

### Target(s)

`server`

### Requirement to close

No error alerts after running `cargo watch -x run`.

### PR commit requirements for a bounty claim

<N/A if not a bounty PR; otherwise please describe the number of commits expected and messages expected >

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Hey, sorry for the slow reply on this. The issue is that you do not have the `DATABASE_URL` environment variable set correctly. 

Make sure you bring postgres up with `docker-compose up -d db`

**Comment by liebkne** [comment]
Like I said, I followed the README and everything before that was just OK. I'm not sure what I was missing here.

<img width="1920" alt="Screenshot 2023-11-11 at 09 04 54" src="https://github.com/arguflow/arguflow/assets/5475262/0b2f9b12-234b-4951-879b-0374875bd1e9">
