### ISSUE TITLE
bugfix: CI actions need to work with ImageMagick

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#640]
### Description

Adding ImageMagick broke the CI actions. We need to get that fixed. 

### Target(s)

`server`

### Requirement to close

Make Github CI actions work again with ImageMagick. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by fastfists** [comment]
Decided to just disable the action for the sake of brevity
