### ISSUE TITLE
feature: support Vectara Corpora logic

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#643]
### Description

In some cases users may want to use one server to coordinate multiple Qdrant collections. We should support that for existing Vectara users at the least. 

This only needs to be on the server level. 

### Target(s)

`server`

### Requirement to close

Users can create collections and specify which collection to search via API. 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
@fastfists did this

**Comment by fastfists** [comment]
fa/dataset branch
