### ISSUE TITLE
feature: add tag set input field when creating a single card

### ISSUE THREAD

**Issue by fastfists** [arguflow/arguflow#652]
### Description
Add the tagset input field for the create card page similar to how it is displayed on the UploadFile page looks. Pictures provided below

## Create card page
![image](https://github.com/arguflow/arguflow/assets/32852291/9b554dd0-907f-4f89-b609-4e337af96a35)

## Upload files page
![image](https://github.com/arguflow/arguflow/assets/32852291/7389b6cd-288f-4763-bce6-57c5c3696336)

### Target(s)

`search`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by jeanninedar** [comment]
Hello, we are two students who would like work on this feature. For our university course we are supposed to find an open source project that seems relevant to us and liked the idea of your project. We would use the next 3/4 weeks to work on this feature if that's okay :). This would be our first contribution - we hope that's okay. 

Could you please point us in the right direction where we need to start?

**Comment by jeanninedar** [comment]
> > Hello, we are two students who would like work on this feature. For our university course we are supposed to find an open source project that seems relevant to us and liked the idea of your project. We would use the next 3/4 weeks to work on this feature if that's okay :). This would be our first contribution - we hope that's okay.
> > Could you please point us in the right direction where we need to start?
> 
> This PR can roughly be explained as copying the `tagSet` signal logic from `UploadFile.tsx` to `CreateNewEvidenceForm.tsx`. You need to create the signal, add the `input` element to the form, then modify the `/card` request to include the `tagSet` in the same way that it is in `UploadFile.tsx`.
> 
> Hopefully the screenshots below are helpful.
> 
> ![image](https://user-images.githubusercontent.com/15804464/283892572-94e475c8-93ac-4df6-ace3-c04685739f27.png) ![image](https://user-images.githubusercontent.com/15804464/283892685-7b4cc80e-69bb-4d3e-835e-06e6d1896ac7.png) ![image](https://user-images.githubusercontent.com/15804464/283892835-9f9f1eaf-da1c-4779-a9e2-4114e94d9a9a.png) ![image](https://user-images.githubusercontent.com/15804464/283892930-cd386015-3043-497a-bd82-9b667c8a24d0.png)

Hey @skeptrunedev,
thank you very much for the explanation! That will help us a lot. 
We will look through the files in the next few days and see if we have any further questions.

**Comment by jeanninedar** [comment]
Hello, 

a small update with a problem we are currently facing. We have set up the project locally and installed all dependencies. However, we are still unable to execute the code.

As soon as we try to run
`cd server
cargo watch -x run`
we get the following error message:

```
error: linking with `cc` failed: exit status: 1
  |
  = note: env -u IPHONEOS_DEPLOYMENT_TARGET -u (long list of paths)
.
.
.
= note: ld: library not found for -lpq
          clang: error: linker command failed with exit code 1 (use -v to see invocation)          
error: could not compile 'vault-server' (bin "vault-server") due to previous error
[Finished running. Exit status: 101]

```

PS: We are using a MacBook 

It would be nice if someone could help us :)

**Comment by fastfists** [comment]
Oh this issue is typical when when postgresql is not found `-lpq` is a postgres library "pq" standing for postgres. Try running `brew install postgresql` using [homebrew](https://brew.sh/) and let us know. 

Side note: None of us are using macs currently but we have had people say that `cargo watch -x run --release` or `cargo run --release` also should help out.

Let me know if this helps!

**Comment by fastfists** [comment]
Alternately you can also try compiling and running the code using [docker](https://docs.docker.com/get-docker/) with `docker compose up -d --build server`.  If you have issues running the code in docker we will be able to assist you a lot better.

**Comment by jeanninedar** [comment]
> Oh this issue is typical when when postgresql is not found `-lpq` is a postgres library "pq" standing for postgres. Try running `brew install postgresql` using [homebrew](https://brew.sh/) and let us know.
> 
> Side note: None of us are using macs currently but we have had people say that `cargo watch -x run --release` or `cargo run --release` also should help out.
> 
> Let me know if this helps!

Thank you for your quick reply :).

`Postgresql` is already installed. 

With `cargo run -release` I currently get the error message `Library not loaded: @rpath/libpython3.8.dylib`, but this seems to be an internal problem that shouldn't be too difficult to solve.

I'll get back to you as soon as it works :)!

**Comment by skeptrunedev** [comment]
> > Oh this issue is typical when when postgresql is not found `-lpq` is a postgres library "pq" standing for postgres. Try running `brew install postgresql` using [homebrew](https://brew.sh/) and let us know.
> > Side note: None of us are using macs currently but we have had people say that `cargo watch -x run --release` or `cargo run --release` also should help out.
> > Let me know if this helps!
> 
> Thank you for your quick reply :).
> 
> `Postgresql` is already installed.
> 
> With `cargo run -release` I currently get the error message `Library not loaded: @rpath/libpython3.8.dylib`, but this seems to be an internal problem that shouldn't be too difficult to solve.
> 
> I'll get back to you as soon as it works :)!

I think that you can just run the server in Docker instead of natively on your machine. Try `sudo docker compose up server` in your terminal.

**Comment by jeanninedar** [comment]
> sudo docker compose up server

Hello,

thank you! `docker compose up server` seems to work somehow :). Now we get the error message `connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory`. We have checked if `postgresql` works - which it does and can find `PGSQL.5432`, so it should exist. Unfortunately, the search on StackOverflow didn't get us any further, so we're hoping for your help.

**Comment by skeptrunedev** [comment]
> > sudo docker compose up server
> 
> Hello,
> 
> thank you! `docker compose up server` seems to work somehow :). Now we get the error message `connection to server on socket "/var/run/postgresql/.s.PGSQL.5432" failed: No such file or directory`. We have checked if `postgresql` works - which it does and can find `PGSQL.5432`, so it should exist. Unfortunately, the search on StackOverflow didn't get us any further, so we're hoping for your help.

You also need to `docker compose up -d` to bring up all of the other services you need. Including postgres.

**Comment by jeanninedar** [comment]
> You also need to `docker compose up -d` to bring up all of the other services you need. Including postgres.

Hello,

thank you! `docker compose up -d` worked perfectly. After implementing the changes above, we got this result. Is this what you envisioned? How can we test the functionality? Or should we simply push our branch so someone can check it? 
<img width="962" alt="Bildschirmfoto 2023-12-06 um 11 32 54" src="https://github.com/arguflow/arguflow/assets/36696554/ef441434-b287-4740-ab22-30ee482793c0">

**Comment by densumesh** [comment]
Just push to your branch and make a PR and we will check it out

**Comment by skeptrunedev** [comment]
Hey @jeanninedar, we are looking to close this issue. Are you still working on this?

**Comment by jeanninedar** [comment]
> Hey @jeanninedar, we are looking to close this issue. Are you still working on this?

I'm really sorry. University was very busy last week, so we only got around to replying now. We just wanted to do a PR, but we don't have a branch on your repo and don't have the rights to add a new one. So we don't have a branch on which we can do the PR. As soon as we get the rights, we will be able to do the PR.
