### ISSUE TITLE
bugfix: document order is off on "chat with selected results"

### ISSUE THREAD

**Issue by fastfists** [arguflow/arguflow#655]
### Description

When "chat with selected results" has a single result selected that doesn't include the first result, the first result is always the one that is displayed on the search ui

![Peek 2023-11-16 13-21](https://github.com/arguflow/arguflow/assets/32852291/5b86b096-4b91-471a-a6ec-a94f3684e976)

### Target(s)

`search`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Done in #657
