### ISSUE TITLE
Create CI action to enforce CHANGE_LOG.md update  

### ISSUE THREAD

**Issue by fastfists** [arguflow/arguflow#673]
### Target(s)

`.github/`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
Will re-open once cc works
