### ISSUE TITLE
bugfix: on update, update Qdrant payload

### ISSUE THREAD

**Issue by densumesh** [arguflow/arguflow#676]
### Description

Update qdrant payload when updating a card as we are now storing card data in qdrant.

### Target(s)

`server`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
We should also make sure that we are updating the embedding vector
