### ISSUE TITLE
Search | Recently Created Cards content on homepage is breaking out

### ISSUE THREAD

**Issue by rohit-singh-bisht** [arguflow/arguflow#683]
### Description
The recently added content cards on the homepage are extending beyond their designated space, causing the entire window to become horizontally scrollable.

### Target(s)
search

### Requirement to close
Ensure that the text is confined within the container, preventing any horizontal scrolling of the window.

https://github.com/arguflow/arguflow/assets/82527615/3c3487db-2a32-4d72-836e-b390bd8b26b9

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
It will be a bit before we get to this. Thank you for drawing attention to the issue.

**Comment by fastfists** [comment]
Sorry the current frontend client is on a different fork from the one in this repository so it would be difficult for you to edit it.

**Comment by skeptrunedev** [comment]
@rohit-singh-bisht @rajdip-b this deployment is on ancient version that is impossible to fix right now. We are working on a new release where we will address this. 

Additionally, after the new release we will start accepting open source contributors again. Thanks guys! We really appreciate you all engaging with the project :heart: and are happy to have you!
