### ISSUE TITLE
feature: Allow for DATASETS to have different sizes of embeddings.

### ISSUE THREAD

**Issue by fastfists** [arguflow/arguflow#722]
### Description

Use [named vectors](https://qdrant.tech/documentation/concepts/collections/#collection-with-multiple-vectors) to have users plug in their own embedding models that may have a different size from openai embedding's.

Needed because we switched the collection model to single collection for all datasets, and collections require that all embeddings are same by default unless we use named vectors. Not sure the exact pattern we should follow to solve but this is important.

**Comment by densumesh** [comment]
For custom embedding sizes, we have to enforce that the users are uploading their own vectors and not using ours

**Comment by fastfists** [comment]
I was thinking for this we can just let them change OPENAI_BASE URL to their own localai instance
