### ISSUE TITLE
bugfix: new migration to modify update_files_storage_counts function to account for UPDATE case

### ISSUE THREAD

**Issue by skeptrunedev** [arguflow/arguflow#734]
### Description

The below SQL trigger function does not account for the case when a file is updated. 

When a file is updated, if the size changes, then we must account for that change in this trigger. 

![image](https://github.com/arguflow/arguflow/assets/15804464/c741e415-6bf7-40b2-a76b-92410434a4bd)

### Target(s)

`server`

### Requirement to close

- [ ] PR contains commit named `bugfix: update_files_storage_counts function accounts for UPDATE case` and accurately fixes the issue 

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#arguflow-general:matrix.zerodao.gg)

**Comment by Akshay-Patel-dev** [comment]
Can I try this one?
